# Generated by Django 5.2.7 on 2025-11-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField()),
                ('nights', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='packages/')),
                ('category', models.CharField(choices=[('honeymoon', 'Honeymoon'), ('family', 'Family'), ('adventure', 'Adventure'), ('weekend', 'Weekend Getaway'), ('luxury', 'Luxury'), ('budget', 'Budget')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
