# Generated by Django 5.2.7 on 2025-11-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Packages',
        ),
    ]
