# Generated by Django 5.2.7 on 2025-11-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_booking_itinerary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingPackage',
        ),
    ]
