# Generated by Django 5.2.7 on 2025-11-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
