# Generated by Django 5.2.7 on 2025-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
