# Generated by Django 5.2.7 on 2025-11-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="e.g. 'flaticon-paragliding' or 'flaticon-map'", max_length=100)),
                ('background_image', models.ImageField(upload_to='services/')),
                ('color_class', models.CharField(default='color-1', help_text='e.g. color-1, color-2, color-3...', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
