# Generated by Django 5.2.7 on 2025-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='out_date',
            field=models.DateField(),
        ),
    ]
