# Generated by Django 5.2.7 on 2025-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=155, unique=True)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('rent', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/hotels')),
                ('is_available', models.BooleanField(default=True)),
                ('rent_for', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
