# Generated by Django 5.2.7 on 2025-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='near_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
