# Generated by Django 5.2.7 on 2025-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_near_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='days',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
