# Generated by Django 5.2.7 on 2025-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
