# Generated by Django 5.2.7 on 2025-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutussection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='background_image2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
